# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d6158d08cdbbbf38860dc0db737891cde35592b6b19d6ca66758a1ed5411765a91ecd1e75f0f86590edb2bc9a7c022cfd6c54bcddd1787c24812dee18ffdaf0

test:
  secret_key_base: d4669284dcbbdb60358df2c445a31eac36b6e449d9e803eec09e7fc014eb4799531e21a79c8fa67a27d7dac3f639787afc52bee61197264e0bb0a2b09f7025b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
